### PR TITLE
fix: Update create-claim script to use createACDClaim

### LINKED ISSUE #625: Fix Create-Claim Script

### PR DESCRIPTION
**Pull request by jwicks31**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

### Release
 Semantic release is enabled for this repository. Make sure you follow the right commit message convention. 
 We're using semantic-release's default — [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

## Description of Changes

Fixes #625 

The create-claim script broke when updating to poet-js v5.0.5. 

Moved create[Type of Claim]Claim functions to tests/helpers/utils so that create-claim script can use them without triggering the setUpClaims script.

### CODE REVIEW

**Comment by warrenv** [comment]
What are the package.json and package-lock.json files in here for?

**Comment by jwicks31** [comment]
@warrenv I had to add @types/ramda to be able to run the script.

File: scripts/CreateClaim.ts [hunk 1]
```diff
@@ -1,16 +1,14 @@
...
+import { createACDClaim } from '../tests/helpers/utils'
 
 const main = async () => {
   const attributes = {
     name: process.argv[2] || 'testing claim',
     author: process.argv[3] || 'the tester',
   }
   const client = new Client()
-  const claim = await createClaim(PrivateKeyACD, ClaimType.Work, attributes)
+  const claim = await createACDClaim(attributes);
```
Comment (krobi64) [inline scripts/CreateClaim.ts]: remove `;`
