### PR TITLE
StorageReader: Publish ClaimsNotDownloaded

### LINKED ISSUE #628: Add Publishing of Failed IPFS Claims Downloads to StorageReader
Needed for #376

### PR DESCRIPTION
**Pull request by jwicks31**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

### Release
 Semantic release is enabled for this repository. Make sure you follow the right commit message convention. 
 We're using semantic-release's default — [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

## Description of Changes

Part of #376 Resolves #628 

### Messaging

- Added `publishClaimsNotDownloaded`

### StorageReader

- Added `publishEntryFailureReason`
- Updated `InvalidCalim` Exception to optionally include `failureTime` + IPFSExceptions to include `failureTime`

### CODE REVIEW

**Comment by kennylavender** [comment]
@poetapp/quality-engineering is there anything here that you would like functional/integration tests for, would you like the tests before/with/after this pr. Since PR's now require only a single reviewer and don't require QE being looking at them, I am just trying to make sure we are not adding a bunch of code without missing integration/functional tests.

File: src/StorageReader/ClaimController.ts [hunk 1]
```diff
@@ -95,6 +95,26 @@ export class ClaimController {
         }
       )
 
+    const publishEntryFailureReason = async (
```
Comment (kennylavender) [inline src/StorageReader/ClaimController.ts]: I think this PR can be split. Adjusting current modules to publish failures does not require that anyone is listening to those published messages. The subscribes to those messages can be added after.

Comment (jwicks31) [reply src/StorageReader/ClaimController.ts]: Ok. I was questioning that. I'll split it up.

**Comment by warrenv** [comment]
This PR is already quite large so I'm ok with deferring tests until we can play around with it more.

File: src/StorageReader/Exceptions.ts [hunk 2]
```diff
@@ -12,33 +12,41 @@ export class NoMoreEntriesException extends Error {
 export class InvalidClaim extends Error {
   readonly ipfsFileHash: string
   readonly failureReason: FailureReason
+  readonly failureTime?: number
 
-  constructor(ipfsFileHash: string, failureReason: FailureReason) {
+  constructor(ipfsFileHash: string, failureReason: FailureReason, failureTime?: number) {
```
Comment (kennylavender) [inline src/StorageReader/Exceptions.ts]: Make `failureTime` default to `new Date().getTime()` so that the user of the error does not need to pass it in. Same goes for the other errors in this file and update the users so they do not pass it in.

Comment (jwicks31) [reply src/StorageReader/Exceptions.ts]: @kennylavender  Ok done!

File: src/StorageReader/Exceptions.ts [hunk 3]
```diff
@@ -12,33 +12,41 @@ export class NoMoreEntriesException extends Error {
...
     super()
     this.ipfsFileHash = ipfsFileHash
+    this.failureTime = failureTime
   }
 }
 
 export const errorToIPFSError = (ipfsFileHash: string) => (error: Error) =>
-  isFetchTimeoutError(error) ? new IPFSTimeoutError(ipfsFileHash) : new IPFSGenericError(ipfsFileHash, error)
+  isFetchTimeoutError(error)
+    ? new IPFSTimeoutError(ipfsFileHash, new Date().getTime())
```
Comment (kennylavender) [inline src/StorageReader/Exceptions.ts]: shouldn't need `new Date().getTime()` anymore

File: src/StorageReader/Exceptions.ts [hunk 4]
```diff
@@ -12,33 +12,41 @@ export class NoMoreEntriesException extends Error {
...
+    : new IPFSGenericError(ipfsFileHash, error, new Date().getTime())
```
Comment (kennylavender) [inline src/StorageReader/Exceptions.ts]: shouldn't need `new Date().getTime()` anymore

File: src/Messaging/Messaging.ts [hunk 5]
```diff
@@ -101,4 +101,8 @@ export class Messaging {
       consume(claimIPFSHashPairs)
     })
   }
+
+  publishClaimsNotDownloaded = async (IPFSHashFailure: ReadonlyArray<IPFSHashFailure>) => {
```
Comment (kennylavender) [inline src/Messaging/Messaging.ts]: please make this value `ipfsHashFailure` so that it's not the same as the interface.
